### PR TITLE
Update teamcity formatter for cucumber

### PR DESCRIPTION
**Pull request by ankurcha**
The old format no longer works with current cucumber versions. This edit basically gets thing running again.

### CODE REVIEW

**Comment by mattwynne** [comment]
Is anyone still using this formatter?

**Comment by darrell** [comment]
Thanks!  I didn't know anyone was still using this. I think the current versions of team city have native support.

**Comment by ankurcha** [comment]
We use this mostly because the one that ships with TC sucks. They interpret each step as a separate test and every scenario as a test Suite. That's just misleading when you are trying to find what scenario failed.

**Comment by darrell** [comment]
Great!  I'm glad it's still of use to people.

**Pull request merged**
